### ISSUE TITLE
Channel guides are confusing

### ISSUE THREAD

**Issue by bcardarella** [lancehalvorsen/phoenix-guides#145]
I'd like to voice concern over the nature of the channel guide. While I appreciate the desire to show what is happening on such a low-level I feel most people just won't care about the dispatching, etc... it might be best to show a more concise "here's how to implement channels" guide then the 2nd half of the guide can do more of the lower-level stuff in iex. As-is the current mix feels disjointed and muddies the message for those that just want to jump in.

**Comment by chrismccord** [comment]
I agree we need more material on using channels in practice. Most users don't have to think about the Transport layer so we can replace it with higher level stuff and move it to its own section for those that want to dive deeper/implement their own transport.

**Comment by lancehalvorsen** [comment]
First, let me say that I hear you. For me, of all the parts of Phoenix, this is the most challenging material to present well. Let me take a minute to explain why I wrote what I did.

Throughout all the guides, I've tried to not only present the how and the why, but also to provide tools for people to investigate, verify and debug what they are doing. Think of the Routing Guide; we write a resource, check the routes created with `mix phoenix.routes`, then check the path helpers in iex. The way to continue that pattern with Channels is to write, say, a `join/3` clause, crack open iex, create a socket, dispatch, and verify that we've joined a topic.

Another pattern I've tried to apply consistently is to begin with a small, isolated piece and expand it one small piece at a time. One alternative to what I've done with the Channel Guide is to build a client alongside the server code and have it interact with the channel. I strongly want to avoid this because it violates the pattern, and it means that there's a lot more code to write and explain before people get to see a concept in action.

When looking at other material out there on Channels, much of it has taken the jump right in approach - write this and this and this and voila! you have a channel. My sense was that there wasn't much out there that showed people what's happening on a somewhat deeper level. There also wasn't much out there that showed people how to verify what they are doing, laying the groundwork for debugging when the example code doesn't quit work on the first try. I thought the Channel Guide was an opportunity to address that.

Thanks for being patient with my rational. :^)

One thing that might help is to hoist the link to the example app in Chris' repo to the top with a blurb saying that if you're the type that wants to get your hands dirty in the code right away, take a look there first.

**Comment by lancehalvorsen** [comment]
Ok, now that I wrote that lengthy treatise (apologies), anybody have ideas about what a better quick introduction/channels in practice might look like? I'm totally open to suggestions, and I was stymied for  quite some time before I came to this approach. (There's a reason the Channel Guide took so long. :^) )

**Comment by lancehalvorsen** [comment]
@bcardarella, @chrismccord gave the Channels Guide an entirely new treatment. What do you think? Can we close this?

**Comment by bcardarella** [comment]
:+1: I saw some copy errors I PRd to fix
